defaults: 
  - base_config
  - _self_
  - model: llama_100M
  - tokenizer: llama_bpe_8192
  - data_curriculum: linear_staged_data_split

dataset: 
  name: 'stacking-babylm-2025/babylm2025_text_data'
  subconfig: 'original_strict_gold' # original_strict_small_gold or original_strict_gold

model:
  model_kwargs:
    vocab_size: 8192 # 2048 or 8192 -> 2^11 or 2^13 | 128* or 128*78=9984

experiment: 
  seed: 42
  name: 'test_huggingface_model_upload_${now:%Y-%m-%d_%H-%M}'
  group: 'Debug_Locally'
  offline_run: False
  dry_run: True
  wandb_log_locally: False
  full_determinism: True
  skip_execution_of_eval_scripts_for_debugging: True
  push_to_hub: True

data_preprocessing:
  include_punctuation: True
  join_sentences: True
  max_input_length: 128

trainer:
  batch_size: 32 # across 4 GPUs gives an effective batch size of 128
  lr_scheduler_type: "cosine_with_min_lr"
  lr_scheduler_kwargs: {"min_lr": 1e-4}
  lr: 1e-3
  num_warmup_steps: 100_000
  max_training_steps: 400_000
  eval_blimp: False
  eval_glue: True
  eval_perplexity: True
  max_flops: 20_727_201_792_000

gradual_stacking:
  enabled: False
  k_number_of_stages: 6
  alpha: 0.0
  layer_per_block: 1
  number_non_embedding_params_compute_equivalent_model: 8_433_920
  align_with_staged_data_curriculum: True

continual_pretraining:
  enable_lr_reset: True
  rewarm_fraction: 0.1
  max_rewarm_lr: 5e-4
  data_replay_mode: "all_previous_stages"
  data_replay_fraction: 0.05
  data_replay_decay: 0.5