defaults: 
  - base_config
  - _self_
  - model: llama_10M
  - tokenizer: llama_bpe_8192
  - data_curriculum: linear_staged_data_split

dataset: 
  name: 'stacking-babylm-2025/babylm2025_text_data'
  subconfig: 'original_strict_small_gold'

model:
  model_kwargs:
    vocab_size: 8192

experiment: 
  seed: 42
  name: 'test_staged_data_split_${now:%Y-%m-%d_%H-%M}'
  group: 'Debug_Locally'
  offline_run: False
  dry_run: True
  wandb_log_locally: False

data_preprocessing:
  include_punctuation: True
  join_sentences: True
  max_input_length: 128

trainer:
  batch_size: 32 # across 4 GPUs gives an effective batch size of 128
  lr: 1e-3
  num_warmup_steps: 100_000
  max_training_steps: 400_000
  eval_blimp: False
  eval_glue: False
  eval_msgs: False
  eval_perplexity: True

gradual_stacking:
  enabled: false
  k_number_of_stages: 5
  alpha: 0.0
  layer_per_block: 1